---
- name: Collect facts
  hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: Gathering Facts
      changed_when: False
      tags:
        - always
        - print_action
      setup:

- name: Create groups
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Add boot node to group bcboot"
      changed_when: False
      tags:
        - always
        - print_action
      add_host:
        name: "{{ item }}"
        groups: bcboot
        inventory_dir: "{{ hostvars[item].inventory_dir }}"
      loop: "{{ groups['all'] }}"
      when: '"boot" in hostvars[item]["ansible_hostname"]'
    - name: "Add all nodes to group bcpeers"
      changed_when: False
      tags:
        - always
        - print_action
      add_host:
        name: "{{ item }}"
        groups: bcpeers
        inventory_dir: "{{ hostvars[item].inventory_dir }}"
      loop: "{{ groups['all'] }}"
      when: '"prod" in hostvars[item]["ansible_hostname"] or "boot" in hostvars[item]["ansible_hostname"]'
    - name: "Add monitnoring nodes to group monitoring_peer"
      changed_when: False
      tags:
        - always
        - print_action
      register: _create_group_monitoring
      add_host:
        name: "{{ item }}"
        groups: monitoring_peer
        inventory_dir: "{{ hostvars[item].inventory_dir }}"
      loop: "{{ groups['all'] }}"
      when: '"monitoring" in hostvars[item]["ansible_hostname"]'

- name: "Install Docker and requirement packages"
  hosts: all
  strategy: free
  become: true
  gather_facts: true
  roles:
    - role: tank.docker
  tasks:
    - name: "Install python packages"
      apt:
        name: python3-pip

- name: Converge boot node
  hosts: "*boot*"
  become: true
  vars:
    bc_haya_comp_state_wallet: present
    bc_haya_comp_state_boot: present
    bc_haya_comp_state_bench: present
    install_promstack: true
    bc_haya_node_id: 0
    bc_haya_plugin_randpa: present
  roles:
    - role: tank.blockchain

- name: Converge producer node
  hosts: "*producer*"
  become: true
  vars:
    bc_haya_comp_state_prod: present
    bc_haya_comp_state_bench: present
    install_promstack: true
    bc_polkadot_extra_validator_id: "{{ play_hosts.index(inventory_hostname) | int }}"
    bc_haya_node_id: "{{ play_hosts.index(inventory_hostname) | int }}"
    bc_haya_plugin_randpa: present
  roles:
    - role: tank.blockchain
  tasks:
    - name: "Show bc_haya_node_id"
      tags:
        - update
      debug:
        msg: "{{ bc_haya_node_id }}"

- name: Converge full node
  hosts: "*full*"
  become: true
  vars:
    bc_haya_comp_state_prod: present
    bc_haya_comp_state_bench: present
    install_promstack: true
    bcpeers_size: "{{ groups['bcpeers'] | length | int }}"
    bc_haya_node_id: "{{ play_hosts.index(inventory_hostname) | int + 1 + bcpeers_size | int }}"
    bc_haya_plugin_randpa: present
    bc_haya_isproduction_enabled: "false"
  roles:
    - role: tank.blockchain
  tasks:
    - name: "Show bc_haya_node_id"
      tags:
        - update
      debug:
        msg: "{{ bc_haya_node_id }}"
    - name: "Show bcpeers_size"
      tags:
        - update
      debug:
        msg: "{{ bcpeers_size }}"

- name: Converge monitoring node
  hosts: "*monitoring*"
  become: true
  vars:
    bc_haya_comp_state_monitoring: present
    install_promstack: true
    admin_user: tank
    admin_password: tank
  roles:
    - role: tank.blockchain
  tasks:
    - name: Open grafana tcp port
      ufw:
        rule: allow
        port: 3000
      tags:
        - firewall
